baseURL = "https://www.mozey.co/demo/ts/"
languageCode = "en-us"
title = "mozey/ts"
theme = "ts"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 2